### ISSUE TITLE
Internal server error when slug is missing from URL

### ISSUE THREAD

**Issue by aalpern** [urbanairship/tessera#459]
Tessera generates dashboard URLs with a slug after the dashboard ID. The slug itself is actually meaningless - it's derived from the title, but is ignored, and is there just to make URLs more human-friendly.

However, it's not necessary to load a dashboard, but is assumed in some places.

So - `http://localhost:5000/dashboards/15/what-s-new-in-0-7` and `http://localhost:5000/dashboards/15` both load fine. 

But if you apply a transform with no slug and then pass the transform URL around, it won't load. So going directly to `http://localhost:5000/dashboards/15/d41/transform/Isolate` results in a 500, because the server is assuming a slug will be in the URL. 

```
2015-05-22 10:27:43,000 INFO     [werkzeug] 127.0.0.1 - - [22/May/2015 10:27:43] "GET /dashboards/15/d41/transform/Isolate HTTP/1.1" 500 -
2015-05-22 10:27:43,005 ERROR    [werkzeug] Error on request:
Traceback (most recent call last):
  File "/Users/alpern/tmp/tessera-ts/lib/python2.7/site-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/Users/alpern/tmp/tessera-ts/lib/python2.7/site-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/Users/alpern/tmp/tessera-ts/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/alpern/tmp/tessera-ts/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/alpern/tmp/tessera-ts/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alpern/tmp/tessera-ts/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/alpern/tmp/tessera-ts/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/alpern/tmp/tessera-ts/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/alpern/tmp/tessera-ts/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alpern/tmp/tessera-ts/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/alpern/tmp/tessera-ts/tessera/views.py", line 468, in ui_dashboard_with_slug
    return ui_dashboard(id, slug, path)
  File "/Users/alpern/tmp/tessera-ts/tessera/views.py", line 474, in ui_dashboard
    element, ignore, name = path.split('/')
ValueError: need more than 2 values to unpack
```

**Comment by aalpern** [comment]
Fixed on development branch
