### ISSUE TITLE
tessera run fail after installation from PyPi

### ISSUE THREAD

**Issue by Slach** [urbanairship/tessera#497]
broken dependencies in tessera_client
<pre>
root@local-monitor:~# pip install tessera
root@local-monitor:~# tessera
Traceback (most recent call last):
  File "/usr/local/bin/tessera", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 616, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 629, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 812, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.4.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests==2.3.0'), set(['tessera-client']))
</pre>

**Comment by aalpern** [comment]
Dear github: auto-closing this ticket based on a comment made in a pull request is _not_ what I wanted.

**Comment by aalpern** [comment]
There we go - verified fixed. @Slach  - thanks for the report!
